auth:
  quay.io:
    username: QUAY_USERNAME
    password: QUAY_PASSWORD
images:
  k8s.gcr.io/addon-resizer: quay.io/QUAY_NAMESPACE/addon-resizer
  k8s.gcr.io/metrics-server/metrics-server: quay.io/QUAY_NAMESPACE/metrics-server
  k8s.gcr.io/dns/k8s-dns-node-cache: quay.io/QUAY_NAMESPACE/k8s-dns-node-cache
  k8s.gcr.io/ingress-nginx/controller: quay.io/QUAY_NAMESPACE/ingress-nginx-controller
